//
// Generated file, do not edit! Created by nedtool 5.4 from pkt.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PKT_M_H
#define __PKT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>pkt.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet pkt
 * {
 *     int src_Server;
 *     int dst_Server;
 * 
 *     int src_ToR;
 *     int dst_ToR;
 * 
 *     int index;
 * 
 *     int TotalHopCount; // the direct ToR is 1
 *     int HopCountNow;
 *     int Hop[11];
 * //    int src_AGG;
 * //    int dst_AGG;
 * //    int core;
 * 
 * 
 *     //	int Agre[];
 *     //	int Core[];
 *     int PacketSize;
 *     int no;
 *     int m;
 * 
 *     int retransmission;
 *     //    double st_AGG;
 *     int path;
 * 
 *     int TxIndex;
 *     int GroupToRIndex;
 *     double End2EndStartTime;
 * 
 *     simtime_t PacketNetworkStartTime;
 *     simtime_t PacketEnd2EndStartTime;
 *     int flag_intraToR;
 * 
 *     int flag_ToR2ToR;
 * 
 *     int optNum;
 * 
 *     int flag_last;
 * }
 * </pre>
 */
class pkt : public ::omnetpp::cPacket
{
  protected:
    int src_Server;
    int dst_Server;
    int src_ToR;
    int dst_ToR;
    int index;
    int TotalHopCount;
    int HopCountNow;
    int Hop[11];
    int PacketSize;
    int no;
    int m;
    int retransmission;
    int path;
    int TxIndex;
    int GroupToRIndex;
    double End2EndStartTime;
    ::omnetpp::simtime_t PacketNetworkStartTime;
    ::omnetpp::simtime_t PacketEnd2EndStartTime;
    int flag_intraToR;
    int flag_ToR2ToR;
    int optNum;
    int flag_last;

  private:
    void copy(const pkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const pkt&);

  public:
    pkt(const char *name=nullptr, short kind=0);
    pkt(const pkt& other);
    virtual ~pkt();
    pkt& operator=(const pkt& other);
    virtual pkt *dup() const override {return new pkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrc_Server() const;
    virtual void setSrc_Server(int src_Server);
    virtual int getDst_Server() const;
    virtual void setDst_Server(int dst_Server);
    virtual int getSrc_ToR() const;
    virtual void setSrc_ToR(int src_ToR);
    virtual int getDst_ToR() const;
    virtual void setDst_ToR(int dst_ToR);
    virtual int getIndex() const;
    virtual void setIndex(int index);
    virtual int getTotalHopCount() const;
    virtual void setTotalHopCount(int TotalHopCount);
    virtual int getHopCountNow() const;
    virtual void setHopCountNow(int HopCountNow);
    virtual unsigned int getHopArraySize() const;
    virtual int getHop(unsigned int k) const;
    virtual void setHop(unsigned int k, int Hop);
    virtual int getPacketSize() const;
    virtual void setPacketSize(int PacketSize);
    virtual int getNo() const;
    virtual void setNo(int no);
    virtual int getM() const;
    virtual void setM(int m);
    virtual int getRetransmission() const;
    virtual void setRetransmission(int retransmission);
    virtual int getPath() const;
    virtual void setPath(int path);
    virtual int getTxIndex() const;
    virtual void setTxIndex(int TxIndex);
    virtual int getGroupToRIndex() const;
    virtual void setGroupToRIndex(int GroupToRIndex);
    virtual double getEnd2EndStartTime() const;
    virtual void setEnd2EndStartTime(double End2EndStartTime);
    virtual ::omnetpp::simtime_t getPacketNetworkStartTime() const;
    virtual void setPacketNetworkStartTime(::omnetpp::simtime_t PacketNetworkStartTime);
    virtual ::omnetpp::simtime_t getPacketEnd2EndStartTime() const;
    virtual void setPacketEnd2EndStartTime(::omnetpp::simtime_t PacketEnd2EndStartTime);
    virtual int getFlag_intraToR() const;
    virtual void setFlag_intraToR(int flag_intraToR);
    virtual int getFlag_ToR2ToR() const;
    virtual void setFlag_ToR2ToR(int flag_ToR2ToR);
    virtual int getOptNum() const;
    virtual void setOptNum(int optNum);
    virtual int getFlag_last() const;
    virtual void setFlag_last(int flag_last);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const pkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, pkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PKT_M_H

